App\Entity\Project:
  attributes:
    id:
      groups: ['project_read']
    name:
      groups: ['project_read', 'project_post', 'project_put']
    description:
      groups: ['project_read', 'project_post', 'project_put']
    owner:
      groups: ['project_read', 'project_post']
    createdAt:
      groups: ['project_read']
    updatedAt:
      groups: ['project_read']